### ISSUE TITLE
Should replace Docker Quickstart guide with new content

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#1]
Docker Quickstart guide on https://tyk.io/tyk-documentation/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/ needs to be replaced with : https://github.com/TykTechnologies/tyk-pro-docker-demo

**Comment by marksou** [comment]
This has now been done.

**Comment by smolnikov** [comment]
The docker quickstart page is still on site https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/ and there are the links to this page in google search results. 
Git repo file is also indexed by google https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/get-started/with-tyk-on-premise/installation/docker/docker-quickstart/docker-quickstart.md
