### ISSUE TITLE
Sizing guide

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#10]
For MongoDB and Redis storage.

E.g. How many GB per million requests?

See https://community.tyk.io/t/size-estimates-for-redis-and-mongodb/1047/2

How many instances required for standard setup?

Martin recently provided a response related to this:

Gateway Nodes:
Memory: 4GB
Storage:  Minimal (not dependent for application)
CPU: 4 Cores
 
Dashboard nodes:
Memory: 2GB
Storage: Minimal (not dependent for application)
CPU: 2 cores
 
Pump Nodes:
Memory: 2GB
Storage: Minimal (not dependent for application)
CPU: 2 Cores
 
Redis:
Memory: 7-8GB
Storage: 500GB SSD (if persistence enabled)
CPU: 2 Cores minimum
 
MongoDB:
Memory: 8GB or more
Storage: 3TB SSD
CPU: 2 Cores
 
The gateway sizing here is very generous, 1 2GB/2 core node could probably handle 2k TPS but it may run “hot”.
 
Regarding the deployment of Redis, for HA most of our customers opt for Redis Cluster as opposed to Redis+Sentinel as it’s a little easier to set up.
 
As for data retention, 2 years of data is possible, but at that transaction rate it will generate a lot of data quickly. We’ve sized Mongo’s HD to handle a large amount of data, but would recommend that we provide data management strategies so that they do not need resizing in the future – there are strategies that can be used to ensure that high-level data is retained and granular data is more short-lived.

**Comment by davegarvey** [comment]
Also need info on MongoDB sizing. 1 million requests creates roughly 3-4GB of analytics data. Most data is stored in tyk_analytics collection, so that could be 'capped' to restrict size but will restrict ability to report on historical data.
