### ISSUE TITLE
Full list of error codes/message pairs

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk-docs-hugo#1007]
It would be useful to have a full list of error codes and their message pairs associated with Tyk. 

User has found 400 (when gRPC plugin is down) and 404 (incorrect URL) but an easy one pager with all of them listed would be ideal.

**Comment by christtyk** [comment]
not stale

**Comment by letzya** [comment]
resolved https://tyk.io/docs/error-response-codes/ !!!
