### ISSUE TITLE
OAuth 2 Grant Types return 404 Errors

### ISSUE THREAD

**Issue by rewsmith** [TykTechnologies/tyk-docs-hugo#1040]
The Grant types (Authorization code, Refresh token ...) links on the [OAuth 2 page](https://tyk.io/docs/basic-config-and-security/security/your-apis/oauth-2-0/) all return 404's.

e.g. [Authorization Code](https://tyk.io/docs/basic-config-and-security/security/your-apis/oauth2.0/auth-code-grant/)

**Comment by marksou** [comment]
These have now been fixed as part of the 2.9.3 release.
