### ISSUE TITLE
Missing command description for Tyk-Sync

### ISSUE THREAD

**Issue by jonathanbernal25** [TykTechnologies/tyk-docs-hugo#1069]
Missing command description for tyk-sync under update. Currently reads:

"update      A brief description of your command"

https://tyk.io/docs/advanced-configuration/manage-multiple-environments/tyk-sync/#usage

**Comment by marksou** [comment]
Hi @jonathanbernal25 I'm not sure this is a bug, but a description of the Update command. @buger can you confirm? This probably needs to be raised in the Tyk-Sync repo as it is output from the code, rather than a docs issue.

**Comment by jonathanbernal25** [comment]
@marksou Ah I see, my interpretation of the description was that it was filler text, left to be written-in for the future.

**Comment by marksou** [comment]
This is now fixed. See https://tyk.io/docs/advanced-configuration/manage-multiple-environments/tyk-sync/#update-command. Closing this
