### ISSUE TITLE
GW Hot Restart: though `kill`, not API. Why?

### ISSUE THREAD

**Issue by frederic-danna** [TykTechnologies/tyk-docs-hugo#1077]
In the [hot-restart-tyk-gateway-process.md](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/tyk-configuration-reference/hot-restart-tyk-gateway-process.md) documentation page, we can read:
> To hot-restart a Tyk Gateway process, you simply need to send a SIGUSR2 signal to the process, for example:
>```bash
>sudo kill -SIGUSR2 {gateway-pid}
>```
Why not calling the API, instead? In case the API is down?

**Comment by buger** [comment]
The whole idea of this signal is that it is a standard linux practice, and because of it it can be easily integrated with tools like systems. Additionally, it is needed mostly if you use OSS version, since when used with the dashboard it is reloaded automatically.
