### ISSUE TITLE
2.9.4 Doc Updates

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#1096]
- [x] [ElasticSearch Batch Operations](https://github.com/TykTechnologies/tyk-pump/issues/204) @tbuchaillot 

- [x] RPM Package Keys @alephnull 

- [x] [Pump Health Check](https://github.com/TykTechnologies/tyk-pump/pull/219) @tbuchaillot 

- [x] DocumentDB Support @buger 

- [x] Headers in Cache Keys @buger 

- [x] OAuth Revocation @sredxny 

- [x] [Allow configure whitelist/blacklist ignore option on global and API level](https://github.com/TykTechnologies/tyk/issues/2897) @furkansenharputlu 

- [x] Portal Key editing

Release branch https://github.com/TykTechnologies/tyk-docs/tree/release-2.9.4

**Comment by buger** [comment]
### Allow configure whitelist/blacklist ignore option on global and API level
1. Global config level, `ignore_endpoint_case`: if it is true all endpoints in all APIs will ignore case no matter value of the ignore parameters on API level or endpoint level
2. API level, `ignore_endpoint_case`: if it is true all endpoints in a specific API will ignore case no matter the value of the ignore param on endpoint level
3. Endpoint level, `ignore_case`: if it is set to true, case will be ignored for only that endpoint.

Rephrasing from bottom to top, 3 is important if 1 and 2 are not set. 2 is important if 1 is not set.

**Comment by buger** [comment]
### Pump health check
Added health check endpoint for tyk-pump.
Added `health_endpoint` and `health_port` to pump configuration. Defaults to `/health` and port `8080`.

**Comment by buger** [comment]
### AWS DocumentDB

Since AWS DocumentDB runs with TLS enabled, so it required a way to run it without disabling TLS verification.
DocumentDB use self-signed certs for verification, and provide a bundle with root certificates for verification, so we need a way to load this bundle.
Additionally DocumentDB can't be exposed to the local machine outside of VPC, which meant that even if verification is turned on, it will always fail since if we use ssh tunnel or similar, domain will differ from original.
Plus it can have mutual TLS enabled.

In order to support it, we provide the following variables for Tyk Analytics and Tyk Pump:

- `mongo_ssl_ca_file` - path to the PEM file with trusted root certificates
- `mongo_ssl_pem_keyfile` - path to the PEM file which contains both client certificate and private key. Required for MutualTLS.
- `mongo_ssl_allow_invalid_hostnames` - ignore hostname check when it differ from origin (in cases with ssh tunneling). The rest of TLS verification still performed.

Working DocumentDB setup looks like this (assuming that there is SSH tunnel, proxying to 27018 port).

```
    "mongo_url": "mongodb://testest:testtest@127.0.0.1:27018/tyk_analytics",
    "mongo_use_ssl": true,
    "mongo_ssl_insecure_skip_verify": false,
    "mongo_ssl_ca_file": "/Users/leonidbugaev/Downloads/rds-combined-ca-bundle.pem",
    "mongo_ssl_allow_invalid_hostnames": true,
```

**Comment by buger** [comment]
### Headers in cache keys

- cache plugin on API level has new `cache_by_headers` field, to use header values as part of cache key. Example value: `["User-Agent"]`
- now you can configure `cache_response_codes` on cache plugin level, in addition to api level

**Comment by tbuchaillot** [comment]
### ElasticSearch Batch Operations

Added the possibility of sending analytics records in bulk requests to ES.
Added inside ES configuration:
`disable_bulk` - Disable batch writing. Defaults to `false`.
`bulk_config`: Batch writing trigger configuration. Each option is an OR with eachother:
- `wokers`: Number of workers. Defaults to` 1.`
- `flush_interval`: Specifies the time in seconds to flush the data and send it to ES. Default `disabled`.
- `bulk_actions`: Specifies the number of requests needed to flush the data and send it to ES. Defaults to `1000 requests`. If it is needed, can be disabled with `-1`.
- `bulk_size`: Specifies the size (in bytes) needed to flush the data and send it to ES. Defaults to `5MB`. If it is needed, can be disabled with `-1`.

**Comment by sredxny** [comment]
## Oauth Revocation

####  Revoke Oauth tokens

This feature gives the ability to users (developers and dashboard users) to revoke oauth tokens, it can be to specific tokens by providing the token and token hint (access_token or refresh_token) or revoke all the tokens providing the oauth Client. This feature is accessible at many levels: endpoint exposed in gateway (in compliance with https://tools.ietf.org/html/rfc7009 ), dashboard API level, Portal developer API and in dashboard from the 'developers page'

### ENDPOINTS IN GATEWAY
Were added 2 endpoints (revoke single token and revoke all tokens) at Tyk Rest API endpoints that will be consumed by the dasboard, in the same way that were added for each API that have relation with an Oauth client. The description is as next:

#### Revoke single token endpoint (consumed by dashboard):
- Method: POST
- Path: tykgateway.com/tyk/oauth/revoke
- Content type: application/x-www-form-urlencoded
- Path Params: None
- Body:
    - token: token to be revoked. String value and required
    - client_id: oauth client ID to where the token belongs. String value and required
    - token_type_hint: type of token to be revoked, if sent then the accepted values are: access_token and refresh_token. String value and optional, of not provided then it will attempt to remove access and refresh tokens that matchs.
#### Revoke all tokens endpoint (consumed by dashboard):
- Method: POST
- Path: tykgateway.com/tyk/oauth/revoke_all
- Content type: application/x-www-form-urlencoded
- Path Params: None
- Body:
    - client_id: Id of the oauth client that we want to revoke all the tokens
    - client_secret: secret of the oauth client, used to check validity of the request
#### Revoke single token for api handler (in compliance wiith RFC 7009):
- Method: POST
- Path: /:api_listen_path/oauth/revoke
- Content type: application/x-www-form-urlencoded
- Path Params: api_listen_path to route the request to the proper handler
- Body:
    - token: token to be revoked. String value and required
    - token_type_hint: type of token to be revoked, if sent then the accepted values are: access_token and refresh_token. String value and optional, of not provided then it will attempt to remove access and refresh tokens that matchs.
#### Revoke all tokens for api handler
- Method: POST
- Path: /:api_listen_path/oauth/revoke_all
- Content type: application/x-www-form-urlencoded
- Path Params: api_listen_path
- Body:
    - client_id: Id of the oauth client that we want to revoke all the tokens
    - client_secret: secret of the oauth client, used to check validity of the request

### ENDPOINTS IN DASHBOARD

#### Revoke all tokens for a developer from developers page (http://tyk-dashboard:3000/#/portal/developers/)
Made for those users who has rights to developers page, this allow dashboard users to revoke all the tokens for an oauth client of a developer
- Method: POST
- Path: /portal/developers/oauth/:devId/:apiId/:appId/revoke_all
- Path Params: 
    - devId: id of the developer, this value is used to check that this developer owns the oauthClient
    - apiId: id of the API to which the oauth client belongs
    - appId: id of the oauth client that we want to revoke all the tokens
- Body: None

#### Revoke single token from portal
- Method: POST
- Path: tyk-portal.com/portalSlug/oauth-clients/:appId/revoke
- Content type: application/json
- Path Params: 
    - appId: id of the oauth client that we want to revoke all the tokens
- Body:
    - token: token to be revoked, is a string value and is required
    - token_type_hint: token type to be revoked, is an optional value. Accepted values are: access_token and refresh_token, if not provided then we will attempt to remove this token without consider the type.

#### Revoke all tokens from portal
- Method: POST
- Path: tyk-portal.com/portalSlug/oauth-clients/:appId/revoke_all
- Content type: application/json
- Path Params: 
    - appId: id of the oauth client that we want to revoke all the tokens
- Body:
    - client_secret: secret of oauth client, this is to validate the request

#### Revoke single token from Dashboard API
- Method: POST
- Path: tyk-dashboard.com/api/apis/oauth/:appId/revoke
- Content type: application/json
- Path Params: 
    - appId: id of the oauth client that we want to revoke all the tokens
- Body:
    - token: token to be revoked, is a string value and is required
    - token_type_hint: token type to be revoked, is an optional value. Accepted values are: access_token and refresh_token, if not provided then we will attempt to remove this token without consider the type.

#### Revoke all tokens from Dashboard API
- Method: POST
- Path: tyk-dashboard.com/api/apis/oauth/:apiId/:appId/revoke_all
- Content type: application/json
- Path Params: 
    - appId: id of the oauth client that we want to revoke all the tokens
- Body:
    - client_secret: secret of oauth client, this is to validate the request

### Frontend
At frontend level was added the ability to revoke the tokens as seen below:

Checking the Oauth Client in edit mode:
![76186095-41fae700-61f7-11ea-9f2c-c870ca1da5bb](https://user-images.githubusercontent.com/4504205/76465624-1113e100-63b4-11ea-9f51-b22ecf87147a.png)

Checkin the portal-developer in edit mode:
![76186098-44f5d780-61f7-11ea-804c-839fb549a255](https://user-images.githubusercontent.com/4504205/76465648-13763b00-63b4-11ea-9198-2249c461ccf7.png)

Revoking tokens from developer portal for a given oauth client
<img width="1324" alt="Captura de Pantalla 2020-03-12 a la(s) 1 48 05 p  m" src="https://user-images.githubusercontent.com/4504205/76556760-29453800-6468-11ea-8f10-ab32206cadcb.png">

**Comment by marksou** [comment]
@buger @sredxny Should we add the calls in the appropriate pages we have already, and just link to them from a revoke OAuth token page?

**Comment by buger** [comment]
### Key editing

Now you can edit keys, if multiple key subscriptions mode is turned on.
When you edit the key, you can remove access to existing APIs or subscribe to the new ones (only of the same type). If new API requires key approval, the new key request will be generated, and access to this API will be granted only after admin approves it.

![image](https://user-images.githubusercontent.com/14009/77554870-ac827700-6ec7-11ea-9729-c9ffeebc22fd.png)
