### ISSUE TITLE
RHEL instructions error

### ISSUE THREAD

**Issue by matiasinsaurralde** [TykTechnologies/tyk-docs-hugo#113]
While investigating an issue with RHEL setup, I've found that the step 3 in our guide is broken, it's [here](https://tyk.io/docs/get-started/with-tyk-on-premise/installation/redhat-rhel-centos/gateway/).

This URL is returning 404.
```
$ wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
```

**Comment by marksou** [comment]
We've now updated the EPEL install instructions on RHEL.
