### ISSUE TITLE
Documented what the gateway and dashboard can and can’t do in hybrid approach

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#1145]
For instance:
1. Use Admin APIs
2. Update API ID with `PUT /api/apis/{api-id}`
3. Oauth endpoints
4. [Custom Analytics in hybrid ](https://tyk.io/docs/release-notes/version-2.8/#custom-analytics-storage-engines-for-multi-cloud--enterprise-mdcb-users)
5. Explain the diff of pump in on-prem vs hybrid with no pump - The only difference is that the periodic job which send analytics is running inside the GW and not as the pump. 
6. API Ownership in turned on for all SaaS users and per license for on-prem
7. tyk-sync and api/policy ID

**Comment by rewsmith** [comment]
7. Dashboard/Portal SSO is not enabled by default in hybrid.  It is an extra (paid) feature which customers can request.  Presently TIB must be run locally to support SSO in Hybrid, but in future (2.10?) TIB will be fully integrated into Dashboard.

**Comment by rewsmith** [comment]
8. Custom dashboard and portal login URLs (sso_custom_login_url and sso_custom_portal_login_url)
