### ISSUE TITLE
Github repository link broken

### ISSUE THREAD

**Issue by padmaraj85** [TykTechnologies/tyk-docs-hugo#1155]
For below page in Tyk Documentation, the Github URL is out of date.

https://tyk.io/docs/try-out-tyk/tutorials/create-api/

The link is still referring to `.md` file instead of `.mmark` file.

<img width="1209" alt="Screenshot 2020-04-16 at 5 08 27 PM" src="https://user-images.githubusercontent.com/38547140/79437641-10024f00-8005-11ea-8c9e-d0d5a2e958c0.png">

**Comment by marksou** [comment]
Hi @padmaraj85 I can't recreate the error you get. From the live site page - https://tyk.io/docs/try-out-tyk/tutorials/create-api/ the Edit on Github button takes me to https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/try-out-tyk/tutorials/create-api.mmark.

**Comment by padmaraj85** [comment]
Hi Mark,
Try to access github from below link. This is the one thats broken.
My bad,  I had given wrong URL in ticket.
https://tyk.io/docs/try-out-tyk/tutorials/create-api-key/
