### ISSUE TITLE
Release 1.3.8 changes

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-docs-hugo#118]
1. Support for custom error messages in middleware using return overrides https://github.com/TykTechnologies/tyk/pull/986. Basically, it is an extension to https://tyk.io/docs/customise-tyk/plugins/rich-plugins/rich-plugins-work/ `ReturnOverides` section. It currently points to the Github pull request, and instead, python code should be embedded to the docs itself (without manifest file).

2. Added new `proxy_default_timeout` option to the Gateway, which specifies default timeout for the request to upstream API. 

3. Added new Dashboard API to verify developer credentials: `/portal/developers/verify_credentials`: with payload like {"username": <login>, "password": <password>}. Should return HTTP code 200 in case of success or 401 if credenials do not match.

4. Extending Tyk section should somehow tell that it is possible to build completely custom developer portal, pointing to this tutorial https://github.com/TykTechnologies/tyk-custom-portal. It is up to you if you would like to move all the documentation to page in docs, and we refer it from repo readme. Also, we can embed screencast right into the docs page.

**Comment by marksou** [comment]
Release now live, documentation updated
