### ISSUE TITLE
2.10 Weight-based load balancing 

### ISSUE THREAD

**Issue by lghiur** [TykTechnologies/tyk-docs-hugo#1227]
When using a load balancer, now you can specify different weights for the different URLs. For example, for testing purpose, you can send 10% of traffic to a beta environment, and 90% to the production environment.
![image](https://user-images.githubusercontent.com/14009/83531767-09b52d00-a4f6-11ea-9960-955fc7f98580.png)

**Comment by marksou** [comment]
I updated the docs when doing the screenshot updates
