### ISSUE TITLE
2.10 Ability to shard analytics to different data-sinks

### ISSUE THREAD

**Issue by lghiur** [TykTechnologies/tyk-docs-hugo#1228]

**Comment by tbuchaillot** [comment]
## Ability to shard analytics to different data-sinks
In a multi-org deployment, each organisation or team, or environment might have their preferred analytics tooling. This capability allows Tyk-Pump, to send analytics for different organisations or APIs to different places. E.g. Org A can send their analytics to MongoDB + DataDog. But Org B can send their analytics to DataDog + expose Prometheus metrics endpoint.

It also becomes possible to put a blacklist in-place, meaning that some data-sinks can receive information for all orgs, whereas other data-sinks will not receive OrgA’s analytics if blacklisted.

## Configuration
This feature adds a new configuration field in each pump called `filters` and its structure is the following:
```
"filters":{
       "api_ids":[],
       "org_ids":[],
       "skip_api_ids":[],
       "skip_org_ids":[]
     }
```
The fields `api_ids` and `org_ids` works as whitelists (APIs and orgs where we want to send the analytics records) and the fields  `skip_api_ids` and `skip_org_ids` works as the opposite (blackslits). 

The priority is always blacklisted configurations over whitelisted.

An example of configuration would be:
 ```
"csv": {
      "type": "csv",
      "filters": {
        "org_ids": ["org1","org2"]
      },
      "meta": {
        "csv_dir": "./bar"
      }
    },
"elasticsearch": {
      "type": "elasticsearch",
      "filters": {
        "skip_api_ids": ["api_id_1"],
       },
      "meta": {
        "index_name": "tyk_analytics",
        "elasticsearch_url": "https://elasticurl:9243",
        "enable_sniffing": false,
        "document_type": "tyk_analytics",
        "rolling_index": false,
        "extended_stats": false,
        "version": "6"
      }
    }
```
With this configuration, all the analytics records related to `org1` or `org2` will go to the `csv` and everything but analytics records from `api_id_1` to `elasticsearch`.

**Comment by ilijabojanovic** [comment]
Verified
