### ISSUE TITLE
TIB Env vars

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk-docs-hugo#1264]
Need categorising:

TYK_IB_SECRET
TYK_IB_PORT
TYK_IB_PROFILEDIR
TYK_IB_BACKEND_PROFILEBACKENDSETTINGS
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_MAXIDLE
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_MAXACTIVE
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_DATABASE
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_PASSWORD
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_ENABLECLUSTER
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_HOSTS
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_USESSL
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_SSLINSECURESKIPVERIFY
TYK_IB_BACKEND_IDENTITYBACKENDSETTINGS_MASTERNAME
TYK_IB_TYKAPISETTINGS_GATEWAYCONFIG_ENDPOINT
TYK_IB_TYKAPISETTINGS_GATEWAYCONFIG_PORT
TYK_IB_TYKAPISETTINGS_GATEWAYCONFIG_ADMINSECRET
TYK_IB_TYKAPISETTINGS_DASHBOARDCONFIG_ENDPOINT
TYK_IB_TYKAPISETTINGS_DASHBOARDCONFIG_PORT
TYK_IB_TYKAPISETTINGS_DASHBOARDCONFIG_ADMINSECRET
TYK_IB_TYKAPISETTINGS_CUSTOMDISPATCHER
TYK_IB_HTTPSERVEROPTIONS_USESSL
TYK_IB_HTTPSERVEROPTIONS_CERTFILE
TYK_IB_HTTPSERVEROPTIONS_KEYFILE
TYK_IB_SSLINSECURESKIPVERIFY
TYK_IB_STORAGE_STORAGETYPE
TYK_IB_STORAGE_MONGOCONF_DBNAME
TYK_IB_STORAGE_MONGOCONF_MONGOURL
TYK_IB_STORAGE_MONGOCONF_MONGOUSESSL
TYK_IB_STORAGE_MONGOCONF_MONGOSSLINSECURESKIPVERIFY
TYK_IB_STORAGE_MONGOCONF_MAXINSERTBATCHSIZEBYTES
TYK_IB_STORAGE_MONGOCONF_MAXDOCUMENTSIZEBYTES
TYK_IB_STORAGE_MONGOCONF_COLLECTIONCAPMAXSIZEBYTES
TYK_IB_STORAGE_MONGOCONF_COLLECTIONCAPENABLE
TYK_IB_STORAGE_FILECONF_FILENAME
TYK_IB_STORAGE_FILECONF_PROFILEDIR

**Comment by marksou** [comment]
This was fixed in #1647
