### ISSUE TITLE
Pump Env Vars

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk-docs-hugo#1265]
Need categorising:

TYK_PMP_PURGEDELAY
TYK_PMP_DONTPURGEUPTIMEDATA
TYK_PMP_UPTIMEPUMPCONFIG_MONGOURL
TYK_PMP_UPTIMEPUMPCONFIG_MONGOUSESSL
TYK_PMP_UPTIMEPUMPCONFIG_MONGOSSLINSECURESKIPVERIFY
TYK_PMP_UPTIMEPUMPCONFIG_MONGOSSLALLOWINVALIDHOSTNAMES
TYK_PMP_UPTIMEPUMPCONFIG_MONGOSSLCAFILE
TYK_PMP_UPTIMEPUMPCONFIG_MONGOSSLPEMKEYFILE
TYK_PMP_UPTIMEPUMPCONFIG_MONGODBTYPE
TYK_PMP_UPTIMEPUMPCONFIG_COLLECTIONNAME
TYK_PMP_UPTIMEPUMPCONFIG_MAXINSERTBATCHSIZEBYTES
TYK_PMP_UPTIMEPUMPCONFIG_MAXDOCUMENTSIZEBYTES
TYK_PMP_UPTIMEPUMPCONFIG_COLLECTIONCAPMAXSIZEBYTES
TYK_PMP_UPTIMEPUMPCONFIG_COLLECTIONCAPENABLE
TYK_PMP_PUMPS
TYK_PMP_ANALYTICSSTORAGETYPE
TYK_PMP_ANALYTICSSTORAGECONFIG_TYPE
TYK_PMP_ANALYTICSSTORAGECONFIG_HOST
TYK_PMP_ANALYTICSSTORAGECONFIG_PORT
TYK_PMP_ANALYTICSSTORAGECONFIG_HOSTS
TYK_PMP_ANALYTICSSTORAGECONFIG_ADDRS
TYK_PMP_ANALYTICSSTORAGECONFIG_MASTERNAME
TYK_PMP_ANALYTICSSTORAGECONFIG_USERNAME
TYK_PMP_ANALYTICSSTORAGECONFIG_PASSWORD
TYK_PMP_ANALYTICSSTORAGECONFIG_DATABASE
TYK_PMP_ANALYTICSSTORAGECONFIG_TIMEOUT
TYK_PMP_ANALYTICSSTORAGECONFIG_MAXIDLE
TYK_PMP_ANALYTICSSTORAGECONFIG_MAXACTIVE
TYK_PMP_ANALYTICSSTORAGECONFIG_ENABLECLUSTER
TYK_PMP_ANALYTICSSTORAGECONFIG_REDISKEYPREFIX
TYK_PMP_ANALYTICSSTORAGECONFIG_REDISUSESSL
TYK_PMP_ANALYTICSSTORAGECONFIG_REDISSSLINSECURESKIPVERIFY
TYK_PMP_STATSDCONNECTIONSTRING
TYK_PMP_STATSDPREFIX
TYK_PMP_LOGLEVEL
TYK_PMP_HEALTHCHECKENDPOINTNAME
TYK_PMP_HEALTHCHECKENDPOINTPORT

TYK_PMP_REDIS_TYPE
TYK_PMP_REDIS_HOST
TYK_PMP_REDIS_PORT
TYK_PMP_REDIS_HOSTS
TYK_PMP_REDIS_ADDRS
TYK_PMP_REDIS_MASTERNAME
TYK_PMP_REDIS_USERNAME
TYK_PMP_REDIS_PASSWORD
TYK_PMP_REDIS_DATABASE
TYK_PMP_REDIS_TIMEOUT
TYK_PMP_REDIS_MAXIDLE
TYK_PMP_REDIS_MAXACTIVE
TYK_PMP_REDIS_ENABLECLUSTER
TYK_PMP_REDIS_REDISKEYPREFIX
TYK_PMP_REDIS_REDISUSESSL
TYK_PMP_REDIS_REDISSSLINSECURESKIPVERIFY
TYK_PMP_REDIS_TYPE
TYK_PMP_REDIS_HOST
TYK_PMP_REDIS_PORT
TYK_PMP_REDIS_HOSTS
TYK_PMP_REDIS_ADDRS
TYK_PMP_REDIS_MASTERNAME
TYK_PMP_REDIS_USERNAME
TYK_PMP_REDIS_PASSWORD
TYK_PMP_REDIS_DATABASE
TYK_PMP_REDIS_TIMEOUT
TYK_PMP_REDIS_MAXIDLE
TYK_PMP_REDIS_MAXACTIVE
TYK_PMP_REDIS_ENABLECLUSTER
TYK_PMP_REDIS_REDISKEYPREFIX
TYK_PMP_REDIS_REDISUSESSL
TYK_PMP_REDIS_REDISSSLINSECURESKIPVERIFY
PMP_MONGO_MONGOURL
PMP_MONGO_MONGOUSESSL
PMP_MONGO_MONGOSSLINSECURESKIPVERIFY
PMP_MONGO_MONGOSSLALLOWINVALIDHOSTNAMES
PMP_MONGO_MONGOSSLCAFILE
PMP_MONGO_MONGOSSLPEMKEYFILE
PMP_MONGO_MONGODBTYPE
PMP_MONGO_COLLECTIONNAME
PMP_MONGO_MAXINSERTBATCHSIZEBYTES
PMP_MONGO_MAXDOCUMENTSIZEBYTES
PMP_MONGO_COLLECTIONCAPMAXSIZEBYTES
PMP_MONGO_COLLECTIONCAPENABLE

PMP_MONGOAGG_MONGOURL
PMP_MONGOAGG_MONGOUSESSL
PMP_MONGOAGG_MONGOSSLINSECURESKIPVERIFY
PMP_MONGOAGG_MONGOSSLALLOWINVALIDHOSTNAMES
PMP_MONGOAGG_MONGOSSLCAFILE
PMP_MONGOAGG_MONGOSSLPEMKEYFILE
PMP_MONGOAGG_MONGODBTYPE
PMP_MONGOAGG_USEMIXEDCOLLECTION
PMP_MONGOAGG_TRACKALLPATHS
PMP_MONGOAGG_IGNORETAGPREFIXLIST
PMP_MONGOAGG_THRESHOLDLENTAGLIST
PMP_MONGOAGG_STOREANALYTICSPERMINUTE

PMP_MONGO_MONGOURL
PMP_MONGO_MONGOUSESSL
PMP_MONGO_MONGOSSLINSECURESKIPVERIFY
PMP_MONGO_MONGOSSLALLOWINVALIDHOSTNAMES
PMP_MONGO_MONGOSSLCAFILE
PMP_MONGO_MONGOSSLPEMKEYFILE
PMP_MONGO_MONGODBTYPE
PMP_MONGO_COLLECTIONNAME
PMP_MONGO_MAXINSERTBATCHSIZEBYTES
PMP_MONGO_MAXDOCUMENTSIZEBYTES
PMP_MONGO_COLLECTIONCAPMAXSIZEBYTES
PMP_MONGO_COLLECTIONCAPENABLE

**Comment by marksou** [comment]
Now here - https://tyk.io/docs/tyk-pump/tyk-pump-configuration/tyk-pump-environment-variables/
