### ISSUE TITLE
Internal API 

### ISSUE THREAD

**Issue by ViolaMarku** [TykTechnologies/tyk-docs-hugo#1279]
We need to document what the option Internal is about: 
<img width="362" alt="Screenshot 2020-06-10 at 18 39 54" src="https://user-images.githubusercontent.com/31623162/84300125-c8ea9300-ab49-11ea-9af1-99ba30032be4.png">
From Slack we know: This API will not be possible to access via standard methods, only via “tyk://” urls, e.g. looping.

**Comment by marksou** [comment]
Going to include this with #1340 so closing this one.
