### ISSUE TITLE
Incorporate algolia setup into repository

### ISSUE THREAD

**Issue by alephnull** [TykTechnologies/tyk-docs-hugo#1292]
Algolia is used to deliver instant search for the online deployment. The population of the index is done by a couple of Ruby scripts that live only on the Buddy filesystem. 

The code outside git should be checked into git and parameterised so that it can run on any pipeline. Separate Algolia accounts are used for staging and prod.

**Comment by marksou** [comment]
Hi @alephnull we also need to do this for Ara.
