### ISSUE TITLE
Validate Hostname against Common Name doesn't say which field name you use

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#1299]
## Relevant Document

https://tyk.io/docs/basic-config-and-security/security/tls-and-ssl/#validate-hostname-against-common-name

## Describe the error

The doc says:
_Validate Hostname against Common Name
From v2.9.3 you can force the validation of the hostname against the common name, both at the Gateway level via your tyk.conf and at the API level._
You can't set it with no instructions. We need to add the actual config field

**Comment by marksou** [comment]
@letzya Who can let me know the config field?

**Comment by letzya** [comment]
Closing wasn't clear from first glance
