### ISSUE TITLE
Portal API 404s

### ISSUE THREAD

**Issue by rewsmith** [TykTechnologies/tyk-docs-hugo#1377]
## Relevant Document

https://tyk.io/docs/tyk-portal-api/
https://tyk.io/docs/tyk-apis/tyk-portal-api/portal-configuration/

## Describe the error

A number of 404's on the Portal API page:
Portal Policies (https://tyk.io/docs/tyk-apis/tyk-portal-api/portal-policies/)
Pages (under Portal Configuration) https://tyk.io/docs/tyk-apis/tyk-portal-api/portal-configuration/pages

**Comment by marksou** [comment]
@rewsmith These will be fixed when new design is released

**Comment by marksou** [comment]
Fixed with new docs look and feel
