### ISSUE TITLE
Update docs to improve Heroku journey

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#143]
We have some hidden docs right now for the Heroku deployment button for Tyk Hybrid. There a few holes in the docs that we need to update for a more comprehensive guide.

- Add more detail in docs around what happens after deployment on Heroku
- Add link to the Heroku dashboard from the docs (probably to the bit describing what happens after deployment)
- Explain they need to create an API in Tyk dashboard before clicking “Open app” in Heroku (link to Tyk dashboard from docs)
- Review the page content of the page that “View” in the Heroku dashboard links to after deploying, to make it more user friendly. e.g. it links here currently: https://tyk.io/docs/get-started/with-tyk-hybrid/tutorials/ which I think is confusing. It mentions Heroku on this page (but that is another user's contribution).

**Comment by marksou** [comment]
On the last point, it might be worth clarifying that the existing Heroku install uses our Docker image. So change that title to "Installation on Heroku with Docker"?

**Comment by marksou** [comment]
Docs are now updated.
