### ISSUE TITLE
Document what versions of each dep we support in each maintained version

### ISSUE THREAD

**Issue by mvdan** [TykTechnologies/tyk-docs-hugo#168]
Dependencies I can think of, there may be more:

* Go (build dep)
* Redis (gateway runtime dep)
* Mongo (dashboard runtime dep)

We need to at least document what versions of these we support for the current stable release, which would be 2.3.x/1.3.x.

If we ever open an alpha/beta channel (which would be 2.4.x/1.4.x at the moment), we would need docs for that one too.

**Comment by marksou** [comment]
For people wanting to use AWS ElastiCache, the supported Redis versions are:
Clustered Mode Disabled - 2.8.x & 3.2.x
Cluster Mode Enabled - 3.2.x only

**Comment by matiasinsaurralde** [comment]
For Go builds: [1.9](https://golang.org/dl/#go1.9.2).

**Comment by asoorm** [comment]
Dashboard 1.4: Go `<= 1.8.x`
Dashboard master: Go `>= 1.8.x && <= 1.9.x`
