### ISSUE TITLE
Add users - example does not match. Should be POST

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#169]
https://tyk.io/docs/tyk-dashboard-api/users/
![image](https://user-images.githubusercontent.com/3155222/31400379-41e3ef62-ade7-11e7-9647-7b8343f5c246.png)

**Comment by marksou** [comment]
Had spotted that earlier today. Is fixed in next push

**Comment by marksou** [comment]
This is now fixed in the Docs.
