### ISSUE TITLE
Meaning of `admin_secret` in dashboard configuration

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk-docs-hugo#1784]
## Branch/Environment/Version
Dashboard configuration documentation (latest).

## Relevant Document
https://tyk.io/docs/tyk-dashboard/configuration/

## Describe the request
Dashboard doc does not mention usage of `admin_secret` configuration value.

## Additional context
See related. It seems like this was previously an issue which was resolved but has been reintroduced.
* https://github.com/TykTechnologies/tyk/issues/224
* https://github.com/TykTechnologies/tyk-docs/pull/706

**Comment by zalbiraw** [comment]
Hello @l3ender I actually pushed a fix for this earlier today. You can see the commit [here](https://github.com/TykTechnologies/tyk-docs/commit/73b7e8af8d4003f829631de4e0a70873b59a5bd4#diff-2af548b55c5ac98b8a1c1c3f8e44cb38709a34e988c684247b81029f2b173433R238). @marksou can we push the changes to the website and resolve this ticket?

**Comment by zalbiraw** [comment]
The updates have been pushed to the docs site. You view them [here](https://tyk.io/docs/tyk-dashboard/configuration/#admin_secret). Thank you again for raising this @l3ender

**Comment by l3ender** [comment]
Thanks @zalbiraw!
