### ISSUE TITLE
Documentation on separating Control API to different domains or ports

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-docs-hugo#19]
Currently, this functionality described only as few configuration options on https://tyk.io/docs/configure/tyk-gateway-configuration-options/#control_api_hostname page, and it definitely deserves more attention.

Very important that `control_api_hostname` will not work without `enable_api_segregation` turned on (but `control_api_port` will). This may change in future.

**Comment by marksou** [comment]
@buger Have we changed this behaviour now, or does it still need clarifying?

**Comment by buger** [comment]
`enable_api_segregation` was removed in 2.4, and now instead we just check if `control_api_hostname` is non-empty. So you need to merge this 2 options docs.

**Comment by marksou** [comment]
Fixed in https://github.com/TykTechnologies/tyk-docs/pull/242.
