### ISSUE TITLE
batch-requests: body object contents in response example should be escaped.

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-docs-hugo#190]
https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/tyk-rest-api/batch-requests.md

body object should look something like this:

```
"body": "{\n  \"args\": {}, \n  \"headers\": {\n    \"Accept-Encoding\": \"gzip\", \n    \"Authorization\": \"aaaaa\", \n    \"Connection\": \"close\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"Go-http-client/1.1\", \n    \"X-Tyk-Test\": \"1\", \n    \"X-Tyk-Version\": \"1.2\"\n  }, \n  \"origin\": \"::1, 34.238.122.49\", \n  \"url\": \"http://httpbin.org/get\"\n}\n"
```

**Comment by letzya** [comment]
@marksou Search this in the doc:

> "body": "{
  "args": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Authorization": "1dbc83b9c431649d7698faa9797e2900f", 
    "Connect-Time": "2", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "Total-Route-Time": "0", 
    "User-Agent": "Go 1.1 package http", 
    "Via": "1.1 vegur", 
    "X-Request-Id": "6a22499a-2776-4aa1-80c0-686581a8be4d", 
    "X-Tyk-Test": "2", 
    "X-Tyk-Version": "1.2"
  }, 
  "origin": "127.0.0.1, 62.232.114.250", 
  "url": "http://httpbin.org/get"
}"
    },
