### ISSUE TITLE
Link to MongoDB docs is broken

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-docs-hugo#192]
https://tyk.io/docs/tyk-rest-api/batch-requests/

See quote after the `expire_analytics_after` entry which reads

`Important: Tyk will not create the expiry index for you. In order to implement data expiry for your analytics data, ensure that the index is created This is very easily achieved using the MongoDB command line interface [as described here][7].`

**Comment by davegarvey** [comment]
![image](https://user-images.githubusercontent.com/1711419/32871039-c169b606-cab9-11e7-8b86-650b21c11706.png)

**Comment by marksou** [comment]
There are a couple of links that have been broken on this page. I'll include it in the new release docs.

**Comment by marksou** [comment]
Fixed in new release.
