### ISSUE TITLE
There is a direct connection between the dashboard and Redis but the diagram does not reflect it

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#229]
[tyk-components/dashboard](https://tyk.io/docs/concepts/tyk-components/dashboard/)

Clients must understand in order to decide in which network zone each component needs to be and what network flows needed to be opened.

**Comment by LordGG** [comment]
It also applies for https://tyk.io/docs/concepts/tyk-components/pump/
Thank you :)
