### ISSUE TITLE
Inconsistency in docs and UI with regards to usage of the terms `virtual path` and `virtual endpoint`

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#250]
We should use one terminology.
In the UI we have `Virtual Endpoint` While in the docs it’s both.

**Comment by marksou** [comment]
@letzya The use of path is used in the Virtual Endpoint UI. I will check the context of the use of Path versus Endpoint in the docs
![screen shot 2017-12-21 at 08 29 45](https://user-images.githubusercontent.com/1983518/34247159-6ab46ef6-e629-11e7-8d6c-22b005ed769a.png)
