### ISSUE TITLE
Add a Single-Sign-On (SSO) section to the docs

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#263]
There is no clear section for this currently, it's found in sections such as "Integration options", and that is entirely clear IMO.

We should create a section so SSO and have under it:
- SSO using Admin API
- SSO with 3rd party integrations
- SSO using LDAP and TIB
- any others i have missed?

**Comment by marksou** [comment]
Can I suggest we have this within the Security section?

**Comment by nickReyn** [comment]
Whatever you think is best 👍  

We'll soon find out what's best approach when we do some research 👍

**Comment by nickReyn** [comment]
Could even work having the category still child of integration options, but have the group named SSO.

**Comment by buger** [comment]
We already have it here, but for sure it should be more user and seo friendly https://tyk.io/docs/integrate/3rd-party-identity-providers/ and here https://tyk.io/docs/integrate/

**Comment by marksou** [comment]
Here are the list of pages I'll add to the new SSO section. Can anyone think of any more?
https://tyk.io/docs/security/your-apis/openid-connect/
https://tyk.io/docs/integrate/3rd-party-identity-providers/
https://tyk.io/docs/integrate/open-id-connect/
https://tyk.io/docs/dashboard-admin-api/sso/

**Comment by marksou** [comment]
New page added with links to existing pages.
