### ISSUE TITLE
Add docs for Kubernetes quickstart on Hybrid

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#284]
We have one for On-prem here: https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/with-kubernetes/ which leads to https://github.com/TykTechnologies/tyk-kubernetes

We need a slightly different one for doing it on Hybrid, as the process is slightly different.

From a customer call - customer wanted to do this.

**Comment by marksou** [comment]
Are the differences for Hybrid captured anywhere?

**Comment by nickReyn** [comment]
Sorry, @asoorm should be able to advise

**Comment by excieve** [comment]
FYI: https://github.com/TykTechnologies/tyk-hybrid-k8

**Comment by marksou** [comment]
Closing this now.
