### ISSUE TITLE
Third Party Identity Providers

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-docs-hugo#30]
We recently received a ticket regarding issues a user had had following our documentation on how to setup social media account access to the Dashboard (see [here](https://tyk.io/docs/integrate/3rd-party-identity-providers/social-oauth/)). Can the following points please be clarified in our docs?:

1. How would users go about adding a `login with Google` or `login with Facebook` button to the developer login page?
2. What should users fill in the `Client ID` field?
3. What exactly is the Profile Setup process?
4. Does this require the Tyk Identity Broker?

**Comment by marksou** [comment]
This issue was addressed in v2.3.
