### ISSUE TITLE
BUG: Documentation search field doesn't work on IE

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#306]
Browser and device: Microsoft surface Pro - IE 11.64.16299.0

**Steps to reproduce:**
1. Open documentation
2. Click into the docs search box
3. Observe that the search field doesn't allow typing and didn't respond..

**Comment by lghiur** [comment]
@nickReyn I just ran a test on IE11 (https://www.screencast.com/t/gMw0losgT3a) and I wasn't able to reproduce this. 

If this is a Microsoft surface Pro thing, I don't know how to test and fix this

**Comment by nickReyn** [comment]
Ok no worries - let's leave it for later and see if we get any more bug reports

**Comment by ConsM** [comment]
@lghiur this issue is different, it refers to https://tyk.io/docs/

**Comment by lghiur** [comment]
@ConsM then it should sit in another repo, and not be included for this bugmash session :)

**Comment by nickReyn** [comment]
It's in the docs repo guys..where else should it sit?

**Comment by marksou** [comment]
Just tried this on IE 11.192.16299.0. I could type a search term (version) and got no results.
![screenshot 2018-02-14 13 29 03](https://user-images.githubusercontent.com/1983518/36208582-4980fcc0-1191-11e8-95c1-1f5a048d1c52.png)
![screenshot 2018-02-14 13 28 54](https://user-images.githubusercontent.com/1983518/36208584-4999ef8c-1191-11e8-82b3-3f0f2525f9d0.png)

**Comment by nickReyn** [comment]
yep this is similar to what he had, but he could not initiate a search and it did the weird UI thing that it's doing in the first screenshot.

**Comment by marksou** [comment]
@ConsM  Could you have another look at this. This Algolia Community post may shed some light - https://discourse.algolia.com/t/results-not-appearing-when-using-internet-explorer/2899/14
