### ISSUE TITLE
Migrate Tyk Identity Broker docs

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-docs-hugo#31]
Most of our documentation for the Tyk Identity Broker seems to only appear in the [wiki](https://github.com/TykTechnologies/tyk-identity-broker/wiki/The-Broker-API) for its Github repo and not in our official docs. I think it might be a good idea to move this information across so that all of our documentation can be found in the same place.

It's also worth noting that some of this information already appears on the site (e.g., the contents of [this page](https://github.com/TykTechnologies/tyk-identity-broker/wiki/Authenticate-a-user-for-the-dashboard-using-Google-and-a-constraint) can be found [here](https://tyk.io/docs/integrate/3rd-party-identity-providers/social-oauth/)) so we will want to avoid adding duplicate information.

**Comment by marksou** [comment]
The wiki info has now been included here https://tyk.io/docs/integrate/3rd-party-identity-providers/tib-rest-api/
