### ISSUE TITLE
Give guidance on how users should size their infrastructure to use Tyk in docs

### ISSUE THREAD

**Issue by nickReyn** [TykTechnologies/tyk-docs-hugo#310]
From customer insights meeting

### Insight
Lots of customers asking about how they should size their infra to use Tyk. We should give best practice examples for On-prem and hybrid.

### Todo
CE's to put together information to include in docs

**Comment by nickReyn** [comment]
@asoorm assigning to u as you mentioned you were looking at doing this already.

**Comment by marksou** [comment]
I think @davegarvey was also putting a sizing guide together.
