### ISSUE TITLE
Configuration Details out  of sync

### ISSUE THREAD

**Issue by cajund** [TykTechnologies/tyk-docs-hugo#343]
The description here:

https://tyk.io/docs/configure/tyk-gateway-configuration-options/

Does not sync up with the example file here:

https://github.com/TykTechnologies/tyk/blob/master/tyk.conf.example

The latter is much more sparse.

**Comment by buger** [comment]
Hello! You mean you example config include all the possible options, even if they will be turned off?

**Comment by cajund** [comment]
Correct. The reference documentation doesn't feel complete, as some things in the docs are not in the config file, and vice-versa. For example, there is `enable_analytics`, which is a boolean. But then there's `analytics_config`, which is an object. The next line is: `enable_analytics.enable_detailed_recording` which: a) isn't an object, and b) isn't in the example.  

`analytics_config.type` isn't in the docs, but is in the example.

**Comment by buger** [comment]
Well, I'll be frank, the purpose of this configuration example is to run community edition without any dependencies, not to show all options. Additionally, recommended way to configure Tyk (both CE and PRO) is using ./install/setup.sh script. And if you want something custom you have docs with list of available params. Tyk has gazillion different options, and if we include all of them to the configuration file, it can be confusing. 

However, I do see that some options non-obvious in a sense that sometimes not clear what type it is, and how it should be defined, and its definitely needs to be fixed.

Do you have any examples of the software which configuration documentation you like?

**Comment by cajund** [comment]
My issue is with the docs, not necessarily the example file. What led me to this point is that I am looking to run CE, and I am also looking to pull the logs from redis/mongo. I am also talking to the sales team about MDCB, but I am tying to understand some of the lower level operations to decide where I need to go. I was hoping the example file would fill in any blanks. Unfortunately, there are consistency issues in the docs, namely due to naming conventions and the fact that the docs straddle "how to" with "reference." (I mentioned this to Nick on a call last week).

The AWS SDK documentation may be something you can look at as an example. https://docs.aws.amazon.com/sdk-for-go/api/

I know docs are hard, but I am learning more from the chance encounter of postings on the forums (and Martin's excellent explanations) that I am from the docs.
