### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#38]
Enhancement proposal:

At the moment users can only download the Gateway Environment Variables as xlsx.
We could create a page for it as well as for the Dashboard and Pump which they have their own environment variables

**Comment by matiasinsaurralde** [comment]
This is the xlsx file: https://tyk.io/wp-content/uploads/2016/11/Gateway-Environment-Vars.xlsx
It would be nice to have this as a table, so it's searchable, etc. and have different sections for Gateway, Pump and Dashboard.

**Comment by marksou** [comment]
Now created pages for each spreadsheet tab.
