### ISSUE TITLE
Update the Ubuntu installation guide for 16.04 LTS

### ISSUE THREAD

**Issue by excieve** [TykTechnologies/tyk-docs-hugo#402]
Many users try installing Tyk on-premise with Ubuntu 16.04 (which is 2 years old now), while the guides in docs are only tried on 14.04. There are some incompatibilities (e.g. mongodb doesn't install like described in the docs). 14.04 LTS support ends rather soon so it would be nice to catch up.

**Comment by asoorm** [comment]
- [x] MongoDB - #403 
- [ ] Redis
- [ ] Dashboard
- [ ] Pump
- [ ] Gateway

**Comment by marksou** [comment]
@excieve @asoorm Do we still need to address Redis and the rest of the installation?

**Comment by asoorm** [comment]
Yes - I only updated the MongoDB bit so far.

**Comment by letzya** [comment]
@marksou Can we add details on the right way to check logs for ubuntu 16.04+? 
On [this page](https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/) we have instructions for both 14.04 and 16.04  but not in the rest of the guide. could be add it?
For instance [start tyk pump](https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/analytics-pump/#step-4-start-tyk-pump) shows only the `upstart` way ([This](https://tyk.io/docs/get-started/with-tyk-on-premise/#service-logs-availability) is not enough)

maybe we should think on revising this page and put the `Supported Ubuntu versions` as a title that would catch your eye or even duplicate the docs and have it separated for 14.04 and 16.04 - this way the user is forced to check and choose the correct version and will not miss it (We should have 2 separate flows or 2 options every time there’s a difference.)

**Comment by letzya** [comment]
**16.04 - 14.04 Diffs to update**
- [ ] Diff when creating debian package list here https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/dashboard/ for instance - it says `trusty` which is correct for 14.04 but should be also `xenial` for 16.04 ==> should update it everywhere in the docs, not only for mongo.

- [ ] one more - https://tyk.io/docs/get-started/with-tyk-on-premise/installation/on-ubuntu/analytics-pump/#step-4-start-tyk-pump shows how to viewing the logs on 14.04 with upstart but not how to do it on 16.04
