### ISSUE TITLE
Edit URL rewrite section

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#41]
See following Forum post
https://community.tyk.io/t/unable-to-get-rewrite-working/1607/5

See also:
https://community.tyk.io/t/url-rewriting-not-working/1415

**Comment by dskoval** [comment]
#590

**Comment by dskoval** [comment]
Open PR for this #590

**Comment by marksou** [comment]
Following #590 merge, I'm closing this.
