### ISSUE TITLE
Improve Virtual endpoint

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#445]
virtual endpoints:
- [x] 1. Can we please mention to set `enable_jsvm` here https://tyk.io/docs/compose-apis/virtual-endpoints/ and EVERYWHERE we mention jsvm?
- [x] 2. Can you please update the sample to use the name `myVirtualHandler` and not `sampleVirtual`, simply because that’s the default name we give on the UI and would it easier.
- [x] 3. Can we please move the aggregation section https://tyk.io/docs/compose-apis/virtual-endpoints/#an-aggregate-js-function to another page? or to the end?  The section that explain the fields of the virtual endpoint in the apiDef should come *straight* after the first code snip `Virtual Endpoint Functions` https://tyk.io/docs/compose-apis/virtual-endpoints/#virtual-endpoint-functions (and not under the batch) . It doesnt read well, and it’s in the middle of the explanation about regular endpoint.  People that dont want back will miss this explanation and will not see they need to give the same function name in `response_function_name`.
 4. In the `config_data` section:
- [x] 4.1 There’s an extra comma at the end - should be removed.
- [x]  4.2 We can make it a bit more helpful by adding map and numbers
```
{
  "string": "string",
  "map": {
    " key": 3
  },
  "num": 4
}
```

and then in the code

```
function myVirtualHandler (request, session, config) {      
        var responseObject = {
                Body: "THIS IS A  VIRTUAL RESPONSE",
                Headers: {
                    "foo-header": "bar",
                    "map-header": JSON.stringify(config.config_data.map),
                    "string-header": config.config_data.string,
                    "num-header": JSON.stringify(config.config_data.num)
        },
        Code: 200
    }
    return TykJsResponse(responseObject, session.meta_data)
}
```

**Comment by marksou** [comment]
@letzya We need to check the aggregation code as it is not currently validating
