### ISSUE TITLE
Add documentation about Dashboard events

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-docs-hugo#455]
We currently have docs for [Gateway events](https://tyk.io/docs/report-monitor-trigger-events/event-types/), but don't have any for Dashboard events. It would be useful to document this as they offer lots of potential in connecting the Dashboard to other systems.

I don't have any further info on Dashboard events, this would need to be gathered from engineering team.

**Comment by marksou** [comment]
@buger Is this something you can provide for me?

**Comment by davegarvey** [comment]
I should add that Dashboard events work in a similar way to Gateway events in that you can attach handlers such as the webhook handler.

**Comment by lonelycode** [comment]
The events in the dashboard are specific to the organisation object, in the prg object there's an events set of fields:

```
{
	"event_options": {
		"api_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		},
		"key_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		},
		"hashed_key_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		},
		"key_request_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		},
		"password_reset_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		},
		"portal_password_reset_event" : {
			"webhook": "http://endpoint",
			"email": "foo@bar.com"
		}
	}
}
```

When any of those events occur, the trigger evaluates the two targets and then generates payloads to send to those endpoints.

It is not massively sophisticated and is mainly designed for integrations.

The data that gets sent is: 

### API events:

```
        {
		Event: api_event.operation
		Data:  {API_DEFINITION_OBJECT}
	}
```

### Key events (hashed and regular):

```
        {
		"Event": "[hashed_]key_event.operation",
		"Data":  {
                     "Key": "KEY",
                     "Org": "ORG_ID"
                 }
	}
```

They all have the same format, but the payloads are different, obviously. The Key Request events send the actual key request object. The password reset events send the reset URL: `{"ResetUrl": "https://dashboard/reset-url"}`

Operations for keys and APIs are `add`, `update`, or `delete`.

The payloads can't be extended.

The emails have templates (part of the templates directory), and send the sam data as the webhook payload.

**Comment by ilijabojanovic** [comment]
@lonelycode 

we have option in org object:
```
    "event_options": {
        "key_event": {
            "webhook": "",
            "email": "",
            "redis": true
        },
        "key_request_event": {
            "webhook": "",
            "email": "",
            "redis": false
        }
    }
```
"redis": true/false 
Could you explain for what we use this?
