### ISSUE TITLE
Missing images https://tyk.io/docs/get-started/with-tyk-cloud/tutorials/create-api/

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#459]
5 images

**Comment by marksou** [comment]
Not sure what images are missing? I can't see any with broken links.

**Comment by marksou** [comment]
For info, the Cloud, Hybrid and On-Premises Pro tutorials all point to the same include file. Therefore all use the same images.

**Comment by marksou** [comment]
Closed as can't be reproduced.
