### ISSUE TITLE
Replicated but identical tutorials in cloud, hybrid, on-prem-pro

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#460]
Makes it harder to maintain (the cloud has missing images). Can we possibly verify they are all identical (not including CE version) and unite them?

![image](https://user-images.githubusercontent.com/3155222/41480357-1edc17b8-70c6-11e8-82fa-70d17b64d323.png)

**Comment by marksou** [comment]
Same comments as per #459 I can't see any missing images, and the Cloud, Hybrid and On-Prem Pro edition tutorials all point to the same include file, so are identical.

**Comment by marksou** [comment]
Closing as tutorials are identical.
