### ISSUE TITLE
Change to ElasticSearch datastore code sample

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#48]
Feedback from the docs states:
The example elastic search configuration shows the url as “hostname:port” (“localhost:9200”,) whereas it should be “http://hostname:port”. Setting up Elastic search without the http causes an error to occur.

Page in question is: /docs/analyse/other-data-stores/#elasticsearch

Can someone confirm and I'll update the example.

**Comment by ConsM** [comment]
@matiasinsaurralde we discussed this briefly some time ago, have you got any update ?

**Comment by marksou** [comment]
HI, @matiasinsaurralde I'm trying to close down a lot of docs issues. Do you have any further comments on this?
