### ISSUE TITLE
Add docs to explain about adding swagger documentation to the developer portal

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#484]
[The apis docs](https://www.tyk.io/docs/tyk-dashboard-api/portal-developers/
) for the portal should also describe the way to add swagger doc to a catalogue. 

- [ ] Add UI screen grabs (similar to the import of swagger when creating an api) - maybe on another page (not sure)
- [ ] Add rest API call to endpoint */portal/documentation/* for Upload 
- [ ] Add rest API call to endpoint */portal/documentation/* for Delete

**Comment by marksou** [comment]
Hi @letzya Can you add some more detail as I'm not sure what you are requesting here.

**Comment by letzya** [comment]
@marksou done

**Comment by davegarvey** [comment]
There's also the `/api/portal/catalogue` endpoint which deals with catalogues. Could do with documenting that too. It gets called when you visit the Catalogues page in the Dashboard.
