### ISSUE TITLE
dashboard admin api doc requires update

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-docs-hugo#495]
When creating a user using admin api `/admin/users` - it seems as though the password is ignored. a password-less user is always created.

Further, the password doesn’t appear to be validated, because the field is simply ignored.

Yet, the docs state: `https://tyk.io/docs/dashboard-admin-api/users/` that the password for a user can be set via admin API.

The bootstrap.sh script uses the password reset in order to generate the user a password.

Docs should be updated, because they are misleading:

1. When creating a dashboard user with Dashboard Admin API, don't set password
2. Use the password reset functionality in order to generate the user's password

---

User to be generated:
```
$ cat user1.json

{
    "active": true,
    "first_name": "Ahmet",
    "last_name": "Soormally",
    "email_address": "ahmet+test@tyk.io",
    "org_id": "5b296ceb3f03d310fffc9b9d",
    "password": "test3123",
    "user_permissions": {
        "IsAdmin": "admin",
        "ResetPassword": "admin"
    }
}
```

Creating my user:
```
curl -k https://dashboard.ahmet:3000/admin/users/ -H 'Admin-Auth: 12345' -X POST -d @user1.json
{"Status":"OK","Message":"fac7a38432cf420149474366d8dee0e4","Meta":{"api_model":{},"first_name":"Ahmet","last_name":"Soormally","email_address":"ahmet+test@tyk.io","org_id":"","active":true,"id":"5b4b40b2488fbf1882fdf4b2","access_key":"fac7a38432cf420149474366d8dee0e4","user_permissions":{"IsAdmin":"admin","ResetPassword":"admin"},"group_id":""}}
```

Dashboard logs:
```
[Jul 16 08:50:26]  WARN User pasword is empty! Please reset!
[Jul 16 08:50:26]  INFO New user session created
```

**Comment by letzya** [comment]
@marksou Can you please update the docs? This issue had cause a user some delay since the doc is not clear enough

**Comment by marksou** [comment]
@asoorm When you are back from holiday, we need to look at this again.
