### ISSUE TITLE
Allow user to change the port for the API in the Gateway

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#5]
To configure a separate control API port you may set the control_api_port field in tyk.conf
See: https://github.com/TykTechnologies/tyk/pull/423#issuecomment-280358558

**Comment by ConsM** [comment]
Reopening this as there was a confusion, will be included in an other release

**Comment by marksou** [comment]
This feature was included in Gateway v2.4
