### ISSUE TITLE
Explain that the returned id is the object id in mongo and not the api id

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#500]
- [x] Clarify that the api call to get an api is expecting in the path an internal id  and not the api id(similar to the explanation here https://tyk.io/docs/tyk-dashboard-api/api-definitions/#update-api-definition)
- [x] Same explanation for the response you get from the api call to create a new api. The response has  the "Meta" field which is the object id in mongo and not the api id.
Users can find this api Id in mongo and within that object the field `api_id` would be the id of the api.
Alternatively they can get the api_id by making a GET request similar to this 
   > https://tyk.io/docs/tyk-dashboard-api/api-definitions/#sample-request-2

**Comment by marksou** [comment]
Now Fixed.
