### ISSUE TITLE
Clarify that api_id in the endpoint /api/import/swagger/ is the mongodb object_id

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#509]
https://tyk.io/docs/configure/import-apis/#sample-request

- [x] Clarify that the api id is the internal id, i.e. the object id in mongodb, and not `api_id` 
> "api_id": "yourapiid",
- [x]  Fix indentation. it's messed up.

**Comment by marksou** [comment]
@letzya If it is not `api_d`, what is the correct parameter? `api-id`?

**Comment by letzya** [comment]
Don’t change The field name, only the explanation. Does that make sense?
