### ISSUE TITLE
java pre-plugin injects header - does not authenticate user

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-docs-hugo#535]
The Java gRPC middleware example in this tutorial is responsible for injecting a header into the request object.

The example to test the middleware provided indicates that the java plugin performs authentication.

https://tyk.io/docs/customise-tyk/plugins/rich-plugins/grpc/request-transformation-java/#a-nametestingatesting-the-plugin

So either we are missing the auth-component of the tutorial, or we need to show that the header has been injected.

**Comment by marksou** [comment]
@matiasinsaurralde Can you have a look at this?

**Comment by matiasinsaurralde** [comment]
I think it's better to add the authentication code and write a quick explanation in the guide.

**Comment by matiasinsaurralde** [comment]
We could add a small reference to this repository, this includes tests and also the authentication middleware: https://github.com/TykTechnologies/tyk-plugin-demo-java/tree/maven
