### ISSUE TITLE
Fix ReadMe of docker repos (GW, dashboard and pump) and update docker hub accordingly

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#552]
- [ ] Fix Gateway https://github.com/TykTechnologies/tyk-gateway-docker/blob/master/README.md
- [ ] Update https://hub.docker.com/r/tykio/tyk-gateway/
-

- [ ] Fix Dashboard https://github.com/TykTechnologies/tyk-dashboard-docker/blob/master/README.md
- [ ] Update https://hub.docker.com/r/tykio/tyk-dashboard/
-

- [ ] Fix pump https://github.com/TykTechnologies/tyk-pump-docker-pub
- [ ] Update docker hub https://hub.docker.com/r/tykio/tyk-pump-docker-pub/

**Comment by marksou** [comment]
Hi @letzya What are the specific issues with those Readmes.
