### ISSUE TITLE
Docs describing what happens when Mongo is down

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#573]
What happens when
-  the dashboard can continue running with current configuration (I assume)
-  pump will not crash
- redis will not crash since it will drop analytics, and explain the TTL on the keys (dont remember the specifics of this
- When mongo comes back:
  - Will pump continue to work as usual?
  - What happens if pump got restarted during that time
  - any other aspects?

**Comment by letzya** [comment]
The gw can work as long as it doesnt get restarted.
Pump would keep trying to reconnect
Redis will drop analytics
Dash/portal -will not work at all

**Comment by marksou** [comment]
@letzya Does this need adding as a FAQ under the Dashboard?
