### ISSUE TITLE
Add troubleshooting for `context cancelled` error

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-docs-hugo#580]
The error message `http: proxy error: context canceled` can appear in the Gateway log. It would be good to have a troubleshooting page in the docs to provide a recommendation from Tyk on what causes this and how to resolve it.

I believe it is due to the upstream service closing the connection with the Gateway before the response is received, but best to check with engineering to confirm and get recommendation on steps to resolve (if any).

**Comment by tomshy** [comment]
I believe this would be important

**Comment by buger** [comment]
Added FAQ section https://tyk.io/docs/troubleshooting/tyk-gateway/context-canceled/
