### ISSUE TITLE
TYK_GW_SECURITY_CERTIFICATES_CONTROLAPI environment variable is undocumented

### ISSUE THREAD

**Issue by dijitali** [TykTechnologies/tyk-docs-hugo#583]
This doc references a `TYK_GW_SECUIRITY_CERTIFICATES_CONTROLAPI` (sic) environment variable:
https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/security/tls-and-ssl/mutual-tls.md#-tips-and-tricks

But it's not documented:
https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/configure/gateway-env-variables.md

**Comment by marksou** [comment]
@buger @joshblakeley We need to add the above and the JSON equivalent to the Gateway Environment Variables table. Can you let me have that and I'll update the page.

**Comment by joshblakeley** [comment]
Ok, yes please document that env variable and correct the typo in the original page. 

There are actually a few options here i didn't know about.

The json in gateway config is:
`security.certificates.control_api`

**Comment by buger** [comment]
The reason why it is undocumented is that Dashboard does not support it: e.g. connecting to the gateway using client certificate (mutual tls).

**Comment by marksou** [comment]
Is it worth adding this caveat to that section?

**Comment by buger** [comment]
Worth removing it from docs for now I think

**Comment by marksou** [comment]
Ok, will do.
