### ISSUE TITLE
http_server_options configuration is both required for TLS but also "highly experimental"

### ISSUE THREAD

**Issue by dijitali** [TykTechnologies/tyk-docs-hugo#584]
From the [TLS and SSL](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/security/tls-and-ssl/tls-and-ssl.md) section:

> To enable SSL in your Tyk gateway and dashboard, you will need to modify the tyk.conf and tyk_analytics files to include a server options section like so:
>
>     "http_server_options"
>      ...

From: [Tyk Gateway Configuration Options](https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/configure/tyk-gateway-configuration-options.md#-http_server_options):
> this is highly experimental and should only be used for extreme tuning purposes, it is not recommended to be used unless absolutely necessary.
>
>     "http_server_options"
>      ...

**Comment by marksou** [comment]
@buger Do we need to change the "highly experimental" comment in the Gateway Config options?
