### ISSUE TITLE
Improve docs for docker installation

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#593]
https://tyk.io/docs/get-started/with-tyk-on-premise/installation/docker/

In case users need to open ports for Redis and mongodb, it doesn't declare it clearly on the docker hub https://hub.docker.com/r/tykio/tyk-gateway/, https://hub.docker.com/r/tykio/tyk-dashboard. Since it's docs for installing separate containers we should detail the ports of Redis and mongo on our docs or in docker hub.

**Comment by letzya** [comment]
@marksou

**Comment by marksou** [comment]
@letzya I don't have access to edit the Docker Container page. I've added the info in the relevant GitHub Repos. @lonelycode Can you change the Docker Containers to reflect the changes I've made in the Github repos for the Gateway, Dashboard and Pump.
