### ISSUE TITLE
Add "Content-Type" header to cURL examples

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#65]
If the above header is not included in the cURL request, it fails with the following error `{"status":"error","error":"Request malformed"}`

@marksou ping me if you need more information

**Comment by marksou** [comment]
Hi @ConsM Have you got any examples of where the `Content-Type` is missing from sample cURL requests?

**Comment by ConsM** [comment]
@marksou  if i recall this was originally raised for https://tyk.io/docs/tyk-rest-api/token-management/ , but is missing in most sections.
You can see a sample [here](https://tyk.io/docs/tyk-rest-api/token-management/#example-importing-existing-keys-into-tyk) at the first request.

**Comment by marksou** [comment]
@ConsM Is this just for POST and PUT Request Samples?
