### ISSUE TITLE
Document Tyk installation on Docker Swarm

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#652]
We need to have documentation on installing Tyk in a Docker Swarm environment.

**Comment by excieve** [comment]
FYI: https://github.com/TykTechnologies/tyk-pro-docker-demo/blob/master/docker-swarm.md

**Comment by Neirda24** [comment]
@excieve : It is providing a good way to test it yes, but the setup.sh does not provide any way to customize the org creation nor the username nor even worse the password. Therefore if people use this link you provided as a way to setup Tyk on swarm I think they will all have the same password....

Even though having the `Swarm Quickstart` next to the `Kubernetes Quickstart` would be nice I think :)
