### ISSUE TITLE
Session Expiry Comment

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#66]
The post mentions session_expiry, but it is not clear where you must adjust that field. In api definition? In the session when you create the token?
https://tyk.io/tyk-documentation/security/your-apis/token-expiry/

**Comment by Fyb3roptik** [comment]
Just close the ticket with no info? Thanks...

**Comment by buger** [comment]
@Fyb3roptik do you have some questions about it?
I think the changes were made in repo, just forgot to link PR to the ticket.

**Comment by Fyb3roptik** [comment]
Can I please get an example response? Does it send a 498 Status Code?
