### ISSUE TITLE
Signature string comment re HMAC Signatures

### ISSUE THREAD

**Issue by marksou** [TykTechnologies/tyk-docs-hugo#67]
The signatureString requires newlines, but the are not properly shown (escaped) in the go-snippet. It would also be very helpful to have a sample (valid) request + keys + headers (with some debugging values of the intermediate values) which can be used to validate your own implementation.
/docs/security/your-apis/hmac-signatures/

**Comment by buger** [comment]
I would propose move final " "s to new, separate lines

**Comment by marksou** [comment]
@buger This ok?
    // Prepare the signature to include those headers:
    signatureString := strings.ToLower("(request-target): ") + 
    "get / "
    signatureString += strings.ToLower("Date") + ": " + tim + 
    " "
    signatureString += strings.ToLower("X-Test-1") + ": " + "hello" + 
    " "
    signatureString += strings.ToLower("X-Test-2") + ": " + "world"

**Comment by buger** [comment]
Also, you feel free to remove `strings.ToLower` from here, and instead mention in docs, that all headers should be lowercase:
```
 signatureString := "(request-target): " + "get /"
 signatureString += "date:" + tim + " "
 signatureString += "x-test-1:" + "hello" + " "
 signatureString += "x-test-2:" + "world"
```
