### ISSUE TITLE
Import API definition using Swagger

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#7]
This old page contains the old documentation https://tyk.io/docs/tyk-api-gateway-v1-9/importing-apis/, which can be the basis of a new page.

Also, re (check Trello board), we need to explain that importing an API definition using Swagger will result in a whitelist, so if the paths are not exactly right it will result in errors.

**Comment by marksou** [comment]
Now covered here - https://tyk.io/docs/transform-traffic/endpoint-designer/ and https://tyk.io/docs/configure/import-apis/
