### ISSUE TITLE
`.mmark` source files

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-docs-hugo#704]
I found a source file with the `.mmark` extension:

https://github.com/TykTechnologies/tyk-docs/blob/master/tyk-docs/content/tyk-multi-data-centre/setup-master-data-centre.mmark

This causes a problem with the 'Edit on Github' links back from the docs website as they expect `.md`, so clicking on them results in a 404. Recommend standardising all markdown source files to use `.md`.

**Comment by marksou** [comment]
These are the files that enable me to use the include file functionality in Hugo. This doesn't work with the `.md` extension. I did raise this in the Hugo forums over a year ago and the only reply I got was to remove the Edit on GitHub button!

**Comment by marksou** [comment]
Closing this for now
