### ISSUE TITLE
Improve documentation for using JWT auth with individual secrets

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#718]
https://tyk.io/docs/security/your-apis/json-web-tokens/#option-2-individual-jwt-secrets
There is no reference to the UI or any screen grabs of the key management screen

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/3155222/55419542-e3e86d00-556c-11e9-9a6a-1fa1ec89fb56.png">

**Comment by marksou** [comment]
Hopefully covered in https://github.com/TykTechnologies/tyk-docs/pull/754
