### ISSUE TITLE
Add TIB REST API 

### ISSUE THREAD

**Issue by ConsM** [TykTechnologies/tyk-docs-hugo#75]
Add the above section.
More information can be found at it's own section in weDocs

**Comment by marksou** [comment]
@ConsM We added this page for 2.4/1.4. Does this cover what you were mentioning? https://tyk.io/docs/dashboard-admin-api/sso/

**Comment by ConsM** [comment]
@marksou it doesn't look like it covers everything from the section at weDocs I mentioned
