### ISSUE TITLE
In tutorial - move the key creation after policy creation and fix the key creation content

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#773]
This [doc](https://tyk.io/docs/get-started/with-tyk-on-premise/tutorials/tyk-on-premises-pro/create-api-token/) should also demo how to use policy when we creating a key.
At the moment it only adds an api to its access list which is correct but a better would be to first create a policy and then create a key with this policy. 
Using policies for keys is a very powerful feature that some other api gateways don't have

![image](https://user-images.githubusercontent.com/3155222/57092474-6c406600-6d03-11e9-8bfa-4359ee090a35.png)

**Comment by marksou** [comment]
Changes now merged.
