### ISSUE TITLE
Release X.3.6

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-docs-hugo#79]
1) Add new context variable `request_id` to https://tyk.io/tyk-documentation/transform-traffic/request-headers/#request-headers-context-variables. Now we can inject request correlation ID (for example X-Request-ID), for example: `"X-Request-ID":"$tyk_context.request_id". Here is example of `global_headers` with context variables https://github.com/TykTechnologies/tyk/issues/713. It probably make sense to extend docs with this example. 

2) Coprocess middleware (Python, Lua, gRPC), now able to override response code, headers and body using ReturnOverrides. See https://github.com/TykTechnologies/tyk/issues/763 the usage. 

3) Password reset
Added ability to reset user passwords.
By default user can reset only his own password.
Add a new permission ResetPassword, but it can be granted only via the admin API using following new endpoints: `/admin/users/:userId/actions/allow_reset_passwords` `/admin/users/:userId/actions/disallow_reset_passwords`. You need make request using PUT HTTP method
Example: `curl -X PUT -H "admin-auth: <your secret>" http://<dashboard>/admin/users/:userId/actions/allow_reset_passwords`

4) Password recovery
Now it's possible for users to recover dashboard password using email. To enable this feature to ensure that you configure email https://tyk.io/tyk-documentation/configure/outbound-email-configuration/. Do not forget about new `email_backend.dashboard_domain` option which should be your public dashboard hostname.

5) Added support for Mongo SSL protocol for both Dashboard and Pump, using new `mongo_ssl_insecure_skip_verify` and `mongo_use_ssl` boolean variables

6) Dashboard session timeout now configurable using `dashboard_session_lifetime` (seconds) option and reduced to 1 hour by default.

**Comment by marksou** [comment]
Added to documentation.
