### ISSUE TITLE
adding image to email example

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-docs-hugo#796]
Hi Mark,  

I couldn't find any examples of the docs showing how to add an image to the outgoing email templates, such as key approval emails from the dashboard.

Could we add something?

**Comment by ilijabojanovic** [comment]
@sedkis @marksou 

All our email templates are located in tyk_dashboard/portal/email_templates folder

**Comment by sedkis** [comment]
Fixed in:
https://github.com/TykTechnologies/tyk-docs/pull/797
