### ISSUE TITLE
The names of the conf files are not clear to everyone

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#823]
For us it's obvious that  `Tyk.conf == gw service` and `tyk_analytics.conf == dashboard service`.  Dev ops that install and maintain the Tyk platform but also are responsible for 10s of other services suggested that our docs should be clearer when referring to the conf file of the dashboard and the gateway (the pump is pretty clear :) ).
==> I agree - we should address the conf with a more formal and unified way by rewriting the text to the following:
...the [gateway config file](https://github.com/TykTechnologies/tyk-gateway-docker/blob/master/tyk.standalone.conf "tyk.conf") is bla bla and in the [dashboard config file](https://github.com/TykTechnologies/tyk-dashboard-docker/blob/master/tyk_analytics.with_mongo_and_gateway.conf "tyk_analytics.conf") should set field `xyz` as bla bla` 

We should go through ALL our docs and improve that.

**Comment by letzya** [comment]
@asoorm what do you think? maybe you have another idea to make it clearer?

**Comment by asoorm** [comment]
I would prefer renaming the files at the application level.

`tyk.conf` -> `tyk-gateway.json`
`tyk_analytics.conf` -> `tyk-dashboard.json`

That's what I would do. But it needs to be backwards compatible. So maybe we should look for `tyk.conf` if `tyk-gateway.json` does not exist?

Something to be mindful of however is that all the systemd unit files and dev-ops stuff refer to `tyk.conf` So maybe these need to be validated.

**Comment by joshblakeley** [comment]
In the gateway there is 
```
confPaths = []string{
		"tyk.conf",
		// TODO: add ~/.config/tyk/tyk.conf here?
		"/etc/tyk/tyk.conf",
	}
```

That the load function goes through looking for a file to load.

So it's easy to get `tyk-gateway.json` in there too.

https://github.com/TykTechnologies/tyk/blob/0c211d14a8c5a8b91669db9602cd666bc1de4778/gateway/server.go#L95-L99

**Comment by marksou** [comment]
I talked to @davegarvey about this yesterday. He thinks that renaming the conf files without breaking backwards compatibility is doable.
