### ISSUE TITLE
Improve docs for multi VMs 

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#824]
The whole doc is written for a single node setup not for production. We should enhance our docs to include info related to multi-nodes multi machines installation.

- [ ] Improve [deploy tyk to production doc](https://www.tyk.io/docs/deploy-tyk-premise-production) to discuss this (add load balancer, which url of gateway do we set in tyk_analytics.conf, which url of dashboard do I set in tyk.conf if I have 2 dashboards, can I use zero conf, when I can't use zeroconf)
- [ ] Improve Getting started guide
- [ ] Publish case study

**Comment by asoorm** [comment]
- [ ] Separate performance tuning from architecture / configuration
- [ ] Re-factor wording for deploy to production - separate section for DBs
- [ ] Update performance documentation as it is out of date & significantly understates the capability of Tyk.
- [ ] Include (latency P50, P95, P99, Max) for various real-world scenarios
- [ ] Include performance metrics for creating/updating API definitions on production workloads.
- [ ] Include performance metrics with 10% bad client actors - wrong pass, hitting rate-limits etc.
- [ ] Include resource consumption (memory + CPU) as part of performance docs.
