### ISSUE TITLE
Create Looping Examples!

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-docs-hugo#831]
For the docs!

**Comment by joshblakeley** [comment]
What examples do you think would be good to show?

**Comment by sedkis** [comment]
Specifically none come to mind.  But perhaps routing to different APIs (at the endpoint level, API level, or hostname level) based on what's in the payload? say {"CLIENTNAME":"FOO"} takes to FOO API, etc?

**Comment by letzya** [comment]
Things i think should be added to the description of this task @sedkis 
.


We need an example per option:
- [ ] A few that are base on reg exp:
 - With looping to another api
 - With looping to another endpoint in the current api
- [ ] Examples with each type of trigger
- [ ] Examples with "Any" and "All"
- [ ] Example with mismatch of trigger - what in the target url
