### ISSUE TITLE
Dashboard on Red Hat (RHEL) / CentOS refers to MongoDB v3

### ISSUE THREAD

**Issue by dencoded** [TykTechnologies/tyk-docs-hugo#843]
Step 3 https://tyk.io/docs/get-started/with-tyk-on-premise/installation/redhat-rhel-centos/dashboard/#step-3-configure-mongodb suggests to install MongoDB v3 however tha lates stable is v4.

**Comment by marksou** [comment]
@dencoded I posted in the Docs channel the other day that we need to confirm our Ubuntu/RHEL/Centos supported versions. Esp as Ubuntu 14.04 was end of lifed at the end of April. We should do both that and MongoDB version support at the same time (but needs testing).
