### ISSUE TITLE
Tyk can authenticate oidc access_token that are in JWT format

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/tyk-docs-hugo#858]
we can authenticate access_token that are jwt (unlike opaque tokens). 
You just need to put the right audience claim in tyk, i.e. the value of the "aud" claim that your access_token" contains rather than the id_token. 
It's working since there’s no real notion of “client Id” in tyk in this case, it’s just happened to be `client id` in id_token and `api id or name` in `access token`.

**Comment by letzya** [comment]
@marksou can you please add this information to the oidc section?

**Comment by marksou** [comment]
@letzya Do you mean Auth0, instead of audience/aud?
